### ISSUE TITLE
Addon generuje vždy nové připojení

### ISSUE THREAD

**Issue by DollarboyJoe** [palinek/pvr.sledovanitv.cz#101]
Mám addon na android tv boxu v kodi nexus, neustále se generuji na webu slwdovani.tv nová připojení pro stejné zařízení. Jde nějak zafixovat, aby klient byl statický a pořád stejně rozpoznatelný. Musím pořád odmazávat připojená zařízení, aby tv fungovala. Doma box připojen za nat routerem, na chatě lte router a vždy mám plný limit 50 u 50 klientú. Děkuji

**Comment by DollarboyJoe** [comment]
![Uploading Screenshot_20231012_165929_Chrome.jpg…]()

**Comment by DollarboyJoe** [comment]
![Screenshot_20231012_165929_Chrome](https://github.com/palinek/pvr.sledovanitv.cz/assets/5045915/48f238c2-2d0a-4de4-83ba-653324589b44)

**Comment by palinek** [comment]
You don't share any version information (not discarding issue template is very useful), so it's rather difficult to give you any reasonable answer. This addon tries to not create new pairings as far as possible and uses the existing one. 
If you're observing creating new instances, there probably is a failure while logging in with the preexisting pairing info (network outages?). Maybe it can be fixed by setting `Device ID` manually in addon configuration.
